# Generated by Django 6.0 on 2025-12-04 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=20, verbose_name='رمز عبور')),
                ('fname', models.CharField(max_length=35, verbose_name='نام')),
                ('lname', models.CharField(max_length=35, verbose_name='نام خانوادگی')),
            ],
        ),
    ]
